// Code generated by entc, DO NOT EDIT.

package forum

const (
	// Label holds the string label denoting the forum type in the database.
	Label = "forum"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the forum in the database.
	Table = "forums"
)

// Columns holds all SQL columns for forum fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
