// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"graph/ent/forum"
	"strings"

	"github.com/facebook/ent/dialect/sql"
)

// Forum is the model entity for the Forum schema.
type Forum struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Forum) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Forum fields.
func (f *Forum) assignValues(values ...interface{}) error {
	if m, n := len(values), len(forum.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	f.ID = int(value.Int64)
	values = values[1:]
	return nil
}

// Update returns a builder for updating this Forum.
// Note that, you need to call Forum.Unwrap() before calling this method, if this Forum
// was returned from a transaction, and the transaction was committed or rolled back.
func (f *Forum) Update() *ForumUpdateOne {
	return (&ForumClient{config: f.config}).UpdateOne(f)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (f *Forum) Unwrap() *Forum {
	tx, ok := f.config.driver.(*txDriver)
	if !ok {
		panic("ent: Forum is not a transactional entity")
	}
	f.config.driver = tx.drv
	return f
}

// String implements the fmt.Stringer.
func (f *Forum) String() string {
	var builder strings.Builder
	builder.WriteString("Forum(")
	builder.WriteString(fmt.Sprintf("id=%v", f.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Forums is a parsable slice of Forum.
type Forums []*Forum

func (f Forums) config(cfg config) {
	for _i := range f {
		f[_i].config = cfg
	}
}
