// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Country is the predicate function for country builders.
type Country func(*sql.Selector)

// Forum is the predicate function for forum builders.
type Forum func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
